[package]
name = "vilbat/component"
description = "Adaptation of sleitnicks component system"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@0.3.0"
Symbol = "sleitnick/symbol@2.0.0"
Signal = "sleitnick/signal@1.1.0"